### ISSUE TITLE
Expand upon ecosystem partners / contributors with details of engagement status

### ISSUE THREAD

**Issue by pospi** [holo-rea/ecosystem#5]
We need to expand upon the project collaboration status document to get a more structured handle on who is engaged and to what degree. The suggestion from @bhaugen has been to use [CfAs](https://valueflo.ws/introduction/cfa.html), which seems sensible.

The devil in the details is going to be figuring out which actions we want people to take, because it also seems sensible to track multiple. As well as some high-level processes describing the necessary work for adoption. I do want to keep this simple though, so that it can form up a useful index. Here are my suggestions for review:

- (action) project agreed to adopting ValueFlows
- (action) project agreed to implement on HoloREA
- (action) undertaking collaboration on shared UI kits
- (process) protocol has been integrated
- some metadata for "project status" (under development, internal alpha, open alpha, public beta etc)

I also think it might be worth skipping the "negotiating" phase of CfA, since we're pretty much guaranteed to know who all parties are by the time we get to that phase in the case of forming these particular agreements, aren't we? Though I could also be misunderstanding CfA terminology.

**Comment by bhaugen** [comment]
I think for this we need to consider more than one form of conversation. See https://github.com/valueflows/forum.valueflo.ws/issues/131#issuecomment-487407126

[Types of conversations:](https://prezi.com/fxauh7vx915c/4-types-of-conversation/)
* [Conversation for relationship](https://justinwise.co.uk/2013/10/16/speech-acts-3-conversations-for-relationship/)
* [Conversation for possibility](https://justinwise.co.uk/2013/10/17/speech-acts-4-conversations-for-possibility/)
* [Conversation for opportunity aka field narrowing](https://www.mediawiki.org/wiki/Good_meetings#Taxonomy) 
* [Conversation for clarification](https://justinwise.co.uk/2016/05/03/a-conversation-for-clarification/)
* [Conversation to collaborate](http://www.dubberly.com/models/conversation_collaborate.html)
* [Conversation for agreement](http://www.dubberly.com/models/conversation_agreement.html)

Those types of conversation happen at different stages of processes of engagement. What stage do we think we are at, with which potential partner? What is the appropriate conversation at that stage?

Note: most of those conversations do not need to be as formal as a CfA, which wants to be recorded as part of a set of economic flows.

**Comment by bhaugen** [comment]
@pospi 
> I also think it might be worth skipping the "negotiating" phase of CfA, since we're pretty much guaranteed to know who all parties are by the time we get to that phase in the case of forming these particular agreements, aren't we? Though I could also be misunderstanding CfA terminology.

Negotiation in CfA means refining requests and offers by means of proposals and counter-proposals until agreements (reciprocal commitments) are reached or the conversation fails. It's usually a prelude to an economic exchange.

Might be analogous refinements of agreements in other stages of conversation.

**Comment by bhaugen** [comment]
Also, I think we should take the published stages of conversations as an idea and recompose to suit us. 

CfA is probly best used as specified, but all the others are malleable (and optional).

**Comment by pospi** [comment]
I'm going to close this issue- it's kinda the type of work that is out of date by the time you complete it. I can say with reference to my personal experience that adopting a tool like @logseq really aids in this kind of relational comprehension; and that gives me some slightly better information to work with but keeping track of things happening outside of oneself is always a losing battle.

Rather than attempting to create static maps of our ecosystem and interactions therein, I think it best to focus on useful tools which make this kind of information apparent in their operation. That way, we're designing for an active data flow between peers rather than passively sweeping a network for changes.
